### ISSUE TITLE
Error in newsserver with empty NEWS STATS

### ISSUE THREAD

**Issue by FastGeert** [rogerthat-platform/rogerthat-kickserver#5]
```
2016-11-24 15:00:54+0100 [NewsProtocol (TLSMemoryBIOProtocol),16363,91.180.48.236] xxxxxxx@skynet.be -  NEWS STATS:
2016-11-24 15:00:54+0100 [NewsProtocol (TLSMemoryBIOProtocol),16363,91.180.48.236] Unhandled Error
        Traceback (most recent call last):
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 601, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in doRead
            return self._dataReceived(data)
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 221, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 419, in dataReceived
            self._flushReceiveBIO()
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 389, in _flushReceiveBIO
            ProtocolWrapper.dataReceived(self, bytes)
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
            self.wrappedProtocol.dataReceived(data)
          File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
            self.lineReceived(line)
          File "/usr/bin/nuntiuz/kick/news/factory.py", line 116, in lineReceived
            implementation(self, args)
          File "/usr/bin/nuntiuz/kick/news/factory.py", line 184, in _news_stats
            stats = self.factory.news_stats(news_ids, list(self.friends), self.account, callback)
          File "/usr/bin/nuntiuz/kick/news/factory.py", line 403, in news_stats
            for news_id in news_ids:
          File "/usr/bin/nuntiuz/kick/news/factory.py", line 183, in <genexpr>
            news_ids = (long(news_id) for news_id in args.split(' '))
        exceptions.ValueError: invalid literal for long() with base 10: ''

2016-11-24 15:00:54+0100 [NewsProtocol (TLSMemoryBIOProtocol),16363,91.180.48.236] Currently connected users: 165
2016-11-24 15:00:55+0100 [NewsProtocol (TLSMemoryBIOProtocol),16133,212.238.128.124] xxxxxxx@hotmail.com -  PING
2016-11-24 15:00:55+0100 [NewsProtocol (TLSMemoryBIOProtocol),16133,212.238.128.124] Sending line: PONG
```

**Comment by bart-at-mobicage** [comment]
Still happening

```
2016-12-02 09:50:59+0100 [NewsProtocol (TLSMemoryBIOProtocol),194046,78.21.137.254] rolanddekegel@telenet.be -  NEWS STATS: 
2016-12-02 09:50:59+0100 [NewsProtocol (TLSMemoryBIOProtocol),194046,78.21.137.254] Unhandled Error
	Traceback (most recent call last):
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 88, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 601, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in doRead
	    return self._dataReceived(data)
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 221, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 419, in dataReceived
	    self._flushReceiveBIO()
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 389, in _flushReceiveBIO
	    ProtocolWrapper.dataReceived(self, bytes)
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
	    self.wrappedProtocol.dataReceived(data)
	  File "/home/geert/kick.venv/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
	    self.lineReceived(line)
	  File "/usr/bin/nuntiuz/kick/news/factory.py", line 116, in lineReceived
	    implementation(self, args)
	  File "/usr/bin/nuntiuz/kick/news/factory.py", line 184, in _news_stats
	    stats = self.factory.news_stats(news_ids, list(self.friends), self.account, callback)
	  File "/usr/bin/nuntiuz/kick/news/factory.py", line 403, in news_stats
	    for news_id in news_ids:
	  File "/usr/bin/nuntiuz/kick/news/factory.py", line 183, in <genexpr>
	    news_ids = (long(news_id) for news_id in args.split(' '))
	exceptions.ValueError: invalid literal for long() with base 10: ''
```

**Comment by bart-at-mobicage** [comment]
Nevermind, my bad. I thought puppet would also restart the news server, but it didn't
